services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_CONFIG__DB__URL=postgresql+asyncpg://test_user:test_password@postgres:5432/test_db
      - PYTHONPATH=/app/app
    command: ["/app/wait-for-it.sh", "postgres:5432", "--", "uvicorn", "app.main:application", "--host", "0.0.0.0", "--port", "8000"]

  alembic:
    build: .
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["/app/wait-for-it.sh", "postgres:5432", "--"]
    command: ["sh", "-c", "cd app && alembic -c alembic.ini upgrade head"]
    environment:
      - APP_CONFIG__DB__URL=postgresql+asyncpg://test_user:test_password@postgres:5432/test_db
      - PYTHONPATH=/app/app

volumes:
  pgdata:


# docker compose build app
# docker compose up -d

# docker compose down -v
# docker compose up --build -d
# docker compose logs app
# docker compose run --entrypoint /bin/sh alembic
# docker exec -it fastapi-recipe-and-grocery-planner-postgres-1 psql -U test_user -d test_db
# docker-compose run --rm alembic pytest app --disable-warnings -v