services:

  app:
    build:
      context: .
    ports:
      - "5050:8000"
    env_file:
      - app/.env
    environment:
      DATABASE_URL: "{{% DATABASE_URL %}}"
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - .:/app
  
  pg:
    image: postgres:14
    env_file:
      - app/.env
    environment:
      POSTGRES_DB: "{{% POSTGRES_DB %}}"
      POSTGRES_USER: "{{% POSTGRES_USER %}}"
      POSTGRES_PASSWORD: "{{% POSTGRES_PASSWORD %}}"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:

# docker compose build app
# docker compose up -d
# docker compose up --build -d
# docker compose down -v