"""update profile table

Revision ID: 32289814be39
Revises: 5383cf7fead8
Create Date: 2025-09-01 14:46:52.454504

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32289814be39"
down_revision: Union[str, Sequence[str], None] = "5383cf7fead8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(
        op.f("uq_profiles_user_id"), "profiles", ["user_id"]
    )
    op.create_foreign_key(
        op.f("fk_profiles_user_id_users"),
        "profiles",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_profiles_user_id_users"), "profiles", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_profiles_user_id"), "profiles", type_="unique")
    op.drop_column("profiles", "user_id")
    # ### end Alembic commands ###
