"""Initial migration

Revision ID: 3f00c6ea3673
Revises: 
Create Date: 2025-09-12 10:39:34.121689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3f00c6ea3673'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('access_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_access_tokens_user_id_users'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_access_tokens'))
    )
    op.create_index(op.f('ix_access_tokens_created_at'), 'access_tokens', ['created_at'], unique=False)
    op.create_table('profiles',
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id'))
    )
    op.execute(
        """
        INSERT INTO products (name) VALUES
        ('Яблоко'),
        ('Банан'),
        ('Апельсин'),
        ('Груша'),
        ('Киви'),
        ('Ананас'),
        ('Арбуз'),
        ('Дыня'),
        ('Виноград'),
        ('Клубника'),
        ('Малина'),
        ('Черника'),
        ('Смородина'),
        ('Персик'),
        ('Нектарин'),
        ('Манго'),
        ('Папайя'),
        ('Лимон'),
        ('Лайм'),
        ('Авокадо'),
        ('Картофель'),
        ('Морковь'),
        ('Свёкла'),
        ('Томат'),
        ('Огурец'),
        ('Капуста'),
        ('Брокколи'),
        ('Цветная капуста'),
        ('Лук'),
        ('Чеснок'),
        ('Шпинат'),
        ('Петрушка'),
        ('Укроп'),
        ('Сельдерей'),
        ('Фасоль'),
        ('Горох'),
        ('Чечевица'),
        ('Рис'),
        ('Гречка'),
        ('Овсянка'),
        ('Пшено'),
        ('Макароны'),
        ('Хлеб'),
        ('Булка'),
        ('Мука'),
        ('Сахар'),
        ('Соль'),
        ('Перец чёрный'),
        ('Молоко'),
        ('Сыр'),
        ('Творог'),
        ('Сметана'),
        ('Йогурт'),
        ('Масло сливочное'),
        ('Масло растительное'),
        ('Курица'),
        ('Говядина'),
        ('Свинина'),
        ('Рыба'),
        ('Яйцо'),
        ('Колбаса'),
        ('Сосиски'),
        ('Кофе'),
        ('Чай'),
        ('Вода'),
        ('Лимонад'),
        ('Кефир'),
        ('Тушёнка'),
        ('Сгущёнка'),
        ('Шпроты'),
        ('Паштет'),
        ('Соленья'),
        ('Огурчики'),
        ('Кукуруза'),
        ('Перловка'),
        ('Киноа'),
        ('Арахис'),
        ('Миндаль'),
        ('Фундук'),
        ('Кешью'),
        ('Фисташки'),
        ('Семечки подсолнечные'),
        ('Семена мака'),
        ('Паста'),
        ('Хлопья'),
        ('Мюсли'),
        ('Мёд'),
        ('Картофель фри'),
        ('Замороженные овощи'),
        ('Холодец'),
        ('Винегрет'),
        ('Щи'),
        ('Борщ'),
        ('Солянка'),
        ('Окрошка'),
        ('Пельмени'),
        ('Вареники'),
        ('Сырники'),
        ('Оладьи'),
        ('Зефир'),
        ('Пряник'),
        ('Медовик'),
        ('Торт'),
        ('Печенье'),
        ('Шоколад'),
        ('Конфеты'),
        ('Чипсы'),
        ('Майонез'),
        ('Кетчуп'),
        ('Горчица'),
        ('Соевый соус'),
        ('Уксус'),
        ('Оливковое масло'),
        ('Маргарин'),
        ('Желе'),
        ('Варенье'),
        ('Икра'),
        ('Оливье'),
        ('Селёдка под шубой'),
        ('Корейская морковь'),
        ('Шашлык'),
        ('Манты'),
        ('Бородинский хлеб'),
        ('Ржаной хлеб'),
        ('Чёрный хлеб'),
        ('Паштет печёночный'),
        ('Рагу овощное'),
        ('Бекон'),
        ('Булочка с маком'),
        ('Соус'),
        ('Ряженка'),
        ('Пряности'),
        ('Паприка'),
        ('Кумин'),
        ('Базилик'),
        ('Орегано'),
        ('Корица'),
        ('Лавровый лист'),
        ('Розмарин')
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_index(op.f('ix_access_tokens_created_at'), table_name='access_tokens')
    op.drop_table('access_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
