services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ../app:/app/app
    environment:
      - PYTHONPATH=/app/app
    command: ["./wait-for-it.sh", "postgres:5432", "--", "uvicorn", "app.main:application", "--host", "0.0.0.0", "--port", "8000"]

  alembic:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - ../app:/app/app
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--"]
    command: ["sh", "-c", "cd app && alembic -c alembic.ini upgrade head"]
    environment:
      - PYTHONPATH=/app/app

volumes:
  pgdata: